### ISSUE TITLE
When I use this plug-in, I always find some hints. But I don't know how to cancel it

### ISSUE THREAD

**Issue by zhaoyufei11011** [MordFustang21/ide-gopls#4]
When I use this plug-in, I always find some hints. But I don't know how to cancel it

The message is as follows

Your workspace root is D:\code\, but your module root is D:\code\test. Please add D:\code\test as a workspace folder.

i don't know how to add workspace floder in Atom i need you help

**Comment by stamblerre** [comment]
When you use `gopls`, you have to open Atom to the root of your module. So if `D:\code\test` contains a `go.mod` file, you have to open that directory. That should stop the warning from coming up.

**Comment by zhaoyufei11011** [comment]
I've done that, but I still do. Like the following picture 
![QQ截图20200113140219](https://user-images.githubusercontent.com/25892895/72235512-81e58980-360d-11ea-9f99-b3dfb0bb494c.png)

**Comment by stamblerre** [comment]
Thanks for following up - that is definitely a bug. I've actually been working on improvements to that error message in https://golang.org/cl/214420 already, so that should fix this issue. I'm not sure when it will be released in a tagged version, but if you'd like to try it when it's merged, you can download `gopls` at master by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`.

**Comment by zhaoyufei11011** [comment]
ok i know this。thanks for you help
